SnQMusicStore.AspMvc/Models/Modules/Csv/ImportAction.cs
//@CodeCopy
//MdStart

namespace SnQMusicStore.AspMvc.Models.Modules.Csv
{
    public enum ImportAction
    {
        None = 0,
        Insert = 1,
        Update = 2,
        Delete = 4,
    }
}
//MdEnd

SnQMusicStore.AspMvc/Models/Modules/View/DisplayViewModel.cs
//@CodeCopy
//MdStart
using SnQMusicStore.AspMvc.Modules.View;
using System;
using System.Reflection;

namespace SnQMusicStore.AspMvc.Models.Modules.View
{
    public partial class DisplayViewModel : ViewModel, IDisplayViewModel
    {
        static DisplayViewModel()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();

        private ModelObject? displayModel;
        private IEnumerable<PropertyInfo>? displayProperties;

        public ModelObject Model { get; set; }
        public ModelObject DisplayModel
        {
            get => displayModel ?? Model;
            set => displayModel = value;
        }
        public IEnumerable<PropertyInfo> DisplayProperties
        {
            get => displayProperties ?? Array.Empty<PropertyInfo>();
            set => displayProperties = value ?? displayProperties;
        }

        public DisplayViewModel(ViewBagWrapper viewBagInfo, ModelObject model, Type modelType, Type displayType)
            : base(viewBagInfo, modelType, displayType)
        {
            Constructing();
            Model = model;
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();

        public virtual IEnumerable<PropertyInfo> GetHiddenProperties()
        {
            return GetHiddenProperties(DisplayType);
        }
        public virtual IEnumerable<PropertyInfo> GetDisplayProperties()
        {
            return displayProperties ??= GetDisplayProperties(DisplayType);
        }
        public virtual object? GetValue(PropertyInfo? propertyInfo)
        {
            return propertyInfo != null ? GetValue(Model, propertyInfo) : null;
        }
        public virtual string GetDisplayValue(PropertyInfo? propertyInfo)
        {
            return propertyInfo != null ? GetDisplayValue(Model, propertyInfo) : string.Empty;
        }
    }
}
//MdEnd

SnQMusicStore.AspMvc/Models/Modules/View/EditViewModel.cs
//@CodeCopy
//MdStart
using SnQMusicStore.AspMvc.Modules.View;
using System;
using System.Reflection;

namespace SnQMusicStore.AspMvc.Models.Modules.View
{
    public partial class EditViewModel : ViewModel
    {
        static EditViewModel()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        public IdentityModel Model { get; init; }
        public IdentityModel DisplayModel => Model;

        public EditViewModel(ViewBagWrapper viewBagInfo, IdentityModel model, Type modelType, Type displayType)
            : base(viewBagInfo, modelType, displayType)
        {
            Constructing();
            Model = model;
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();

        public virtual IEnumerable<PropertyInfo> GetHiddenProperties()
        {
            return GetHiddenProperties(DisplayType);
        }
        public virtual IEnumerable<PropertyInfo> GetDisplayProperties()
        {
            return GetDisplayProperties(DisplayType);
        }
        public virtual object? GetValue(PropertyInfo propertyInfo)
        {
            return GetValue(Model, propertyInfo);
        }
        public virtual string GetDisplayValue(PropertyInfo propertyInfo)
        {
            return GetDisplayValue(Model, propertyInfo);
        }
    }
}
//MdEnd

SnQMusicStore.AspMvc/Models/Modules/View/FilterModel.cs
//@CodeCopy
//MdStart
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using SnQMusicStore.AspMvc.Modules.Session;
using SnQMusicStore.AspMvc.Modules.View;
using System;
using System.Reflection;

namespace SnQMusicStore.AspMvc.Models.Modules.View
{
    public class FilterModel
    {
        public ISessionWrapper SessionInfo { get; init; }
        public ViewBagWrapper ViewBagInfo => IndexViewModel.ViewBagInfo;
        public IndexViewModel IndexViewModel { get; init; }

        public FilterModel(ISessionWrapper sessionInfo, IndexViewModel indexViewModel)
        {
            SessionInfo = sessionInfo;
            IndexViewModel = indexViewModel;
        }

        public virtual string GetId(PropertyInfo propertyInfo)
        {
            if (ViewBagInfo.GetMappingProperty(propertyInfo.Name, out var property) == false)
            {
                property = propertyInfo;
            }
            var result = ViewBagInfo.ItemPrefix;

            if (result.HasContent())
            {
                result = $"{result}_{property?.DeclaringType?.Name}_{property?.Name}";
            }
            else
            {
                result = $"{property?.DeclaringType?.Name}_{property?.Name}";
            }
            return result;
        }
        public virtual string GetName(PropertyInfo propertyInfo)
        {
            if (ViewBagInfo.GetMappingProperty(propertyInfo.Name, out var property) == false)
            {
                property = propertyInfo;
            }
            var result = ViewBagInfo.ItemPrefix;

            if (result.HasContent())
            {
                result = $"{result}.{property?.DeclaringType?.Name}.{property?.Name}";
            }
            else
            {
                result = $"{property?.DeclaringType?.Name}.{property?.Name}";
            }
            return result;
        }
        public virtual string GetTypeOperationId(PropertyInfo propertyInfo)
        {
            return $"{GetId(propertyInfo)}_{StaticLiterals.TypeOperationPostfix}";
        }
        public virtual string GetTypeOperationName(PropertyInfo propertyInfo)
        {
            return $"{GetName(propertyInfo)}.{StaticLiterals.TypeOperationPostfix}";
        }
        public virtual string GetFieldOperationId(PropertyInfo propertyInfo)
        {
            return $"{GetId(propertyInfo)}_{StaticLiterals.FieldOperationPostfix}";
        }
        public virtual string GetFieldOperationName(PropertyInfo propertyInfo)
        {
            return $"{GetName(propertyInfo)}.{StaticLiterals.FieldOperationPostfix}";
        }

        public SelectList GetFieldOperations()
        {
            var operations = new List<SelectListItem>
            {
                new SelectListItem { Selected = true, Value = string.Empty, Text = string.Empty },
                new SelectListItem { Selected = true, Value = "and", Text = "And" },
                new SelectListItem { Selected = true, Value = "or", Text = "Or" }
            };
            return new SelectList(operations, "Value", "Text");
        }
        public SelectList GetTypeOperations(PropertyInfo? propertyInfo)
        {
            _ = propertyInfo ?? throw new ArgumentNullException(nameof(propertyInfo));

            var translate = ViewBagInfo.Translate;
            var operationItems = new List<SelectListItem>();

            if (ViewBagInfo.GetMappingProperty(propertyInfo.Name, out var property) == false)
            {
                property = propertyInfo;
            }

            operationItems.Add(new SelectListItem { Value = string.Empty, Text = string.Empty });
            if (property?.PropertyType == typeof(string))
            {
                operationItems.Add(new SelectListItem { Value = StaticLiterals.OperationEquals, Text = translate(StaticLiterals.OperationEquals) });
                operationItems.Add(new SelectListItem { Value = StaticLiterals.OperationNotEquals, Text = translate(StaticLiterals.OperationNotEquals) });
                operationItems.Add(new SelectListItem { Value = StaticLiterals.OperationContains, Text = translate(StaticLiterals.OperationContains) });
                operationItems.Add(new SelectListItem { Value = StaticLiterals.OperationStartsWith, Text = translate(StaticLiterals.OperationStartsWith) });
                operationItems.Add(new SelectListItem { Value = StaticLiterals.OperationEndsWith, Text = translate(StaticLiterals.OperationEndsWith) });
            }
            else if (property?.PropertyType == typeof(int))
            {
                operationItems.Add(new SelectListItem { Value = StaticLiterals.OperationNumEquals, Text = translate(StaticLiterals.OperationNumEquals) });
                operationItems.Add(new SelectListItem { Value = StaticLiterals.OperationNumIsGreater, Text = translate(StaticLiterals.OperationNumIsGreater) });
                operationItems.Add(new SelectListItem { Value = StaticLiterals.OperationNumIsLess, Text = translate(StaticLiterals.OperationNumIsLess) });
            }
            else
            {
                operationItems.Add(new SelectListItem { Value = StaticLiterals.OperationEquals, Text = translate(StaticLiterals.OperationEquals) });
            }
            return new SelectList(operationItems, "Value", "Text");
        }
        public FilterValues GetFilterValues(IFormCollection formCollection)
        {
            var result = new FilterValues();

            foreach (var property in IndexViewModel.GetDisplayProperties())
            {
                var operationName = GetTypeOperationName(property);
                var operationValue = formCollection[operationName];

                if (operationValue.Count > 0 && string.IsNullOrEmpty(operationValue[0]) == false)
                {
                    var operandName = GetName(property);
                    var operandValue = formCollection[operandName];

                    if (operandValue.Count > 0 && string.IsNullOrEmpty(operandValue[0]) == false)
                    {
                        var filterItem = new FilterItem()
                        {
                            Name = property.Name,
                            Operation = operationValue,
                            Value = operandValue[0],
                        };
                        result[property.Name] = filterItem;
                    }
                }
            }
            return result;
        }
    }
}
//MdEnd

SnQMusicStore.AspMvc/Models/Modules/View/SorterModel.cs
//@CodeCopy
//MdStart
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using SnQMusicStore.AspMvc.Modules.Session;
using SnQMusicStore.AspMvc.Modules.View;
using System.Reflection;

namespace SnQMusicStore.AspMvc.Models.Modules.View
{
    public class SorterModel
    {
        public ISessionWrapper SessionInfo { get; init; }
        public ViewBagWrapper ViewBagInfo => IndexViewModel.ViewBagInfo;
        public IndexViewModel IndexViewModel { get; init; }

        public SorterModel(ISessionWrapper sessionInfo, IndexViewModel indexViewModel)
        {
            SessionInfo = sessionInfo;
            IndexViewModel = indexViewModel;
        }

        public virtual string GetId(PropertyInfo propertyInfo)
        {
            if (ViewBagInfo.GetMappingProperty(propertyInfo.Name, out var property) == false)
            {
                property = propertyInfo;
            }
            var result = ViewBagInfo.ItemPrefix;

            if (result.HasContent())
            {
                result = $"{result}_{property?.DeclaringType?.Name}_{property?.Name}";
            }
            else
            {
                result = $"{property?.DeclaringType?.Name}_{property?.Name}";
            }
            return result;
        }
        public virtual string GetName(PropertyInfo propertyInfo)
        {
            if (ViewBagInfo.GetMappingProperty(propertyInfo.Name, out var property) == false)
            {
                property = propertyInfo;
            }
            var result = ViewBagInfo.ItemPrefix;

            if (result.HasContent())
            {
                result = $"{result}.{property?.DeclaringType?.Name}.{property?.Name}";
            }
            else
            {
                result = $"{property?.DeclaringType?.Name}.{property?.Name}";
            }
            return result;
        }
        public virtual string GetSortOperationId(PropertyInfo propertyInfo)
        {
            return $"{GetId(propertyInfo)}_{StaticLiterals.SortOperationPostfix}";
        }
        public virtual string GetSortOperationName(PropertyInfo propertyInfo)
        {
            return $"{GetName(propertyInfo)}.{StaticLiterals.SortOperationPostfix}";
        }

        public SelectList GetSortOperations(PropertyInfo? propertyInfo)
        {
            var translate = ViewBagInfo.Translate;
            var operations = new List<SelectListItem>();

            if (propertyInfo != null && ViewBagInfo.GetMappingProperty(propertyInfo.Name, out var property) == false)
            {
                property = propertyInfo;
            }

            operations.Add(new SelectListItem { Value = string.Empty, Text = string.Empty });
            operations.Add(new SelectListItem { Value = StaticLiterals.SortAscending, Text = translate(StaticLiterals.SortAscending) });
            operations.Add(new SelectListItem { Value = StaticLiterals.SortDescending, Text = translate(StaticLiterals.SortDescending) });
            return new SelectList(operations, "Value", "Text");
        }
        public SorterValues GetSorterValues(IFormCollection formCollection)
        {
            var result = new SorterValues();

            foreach (var property in IndexViewModel.GetDisplayProperties())
            {
                var operationName = GetSortOperationName(property);
                var operationValue = formCollection[operationName];

                if (operationValue.Count > 0 && string.IsNullOrEmpty(operationValue[0]) == false)
                {
                    var sorterItem = new SorterItem()
                    {
                        Name = property.Name,
                        Operation = operationValue[0],
                    };
                    result[property.Name] = sorterItem;
                }
            }
            return result;
        }
    }
}
//MdEnd

SnQMusicStore.AspMvc/Controllers/TranslationsController.cs
//@CodeCopy
//MdStart
using Microsoft.AspNetCore.Mvc;
using SnQMusicStore.AspMvc.Modules.Language;
using System.Linq;
using System.Threading.Tasks;

namespace SnQMusicStore.AspMvc.Controllers
{
    public partial class TranslationsController : MvcController
    {
        static TranslationsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();

        public TranslationsController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();

        public IActionResult ReloadTranslations()
        {
            Translator.Instance.ReloadTranslations();

            return RedirectToAction("Index");
        }

        #region Export no translations
        protected override string[] CsvHeader => new string[]
        {
            $"{nameof(Models.ThirdParty.Translation.Id)}",
            $"{nameof(Models.ThirdParty.Translation.AppName)}",
            $"{nameof(Models.ThirdParty.Translation.KeyLanguage)}",
            $"{nameof(Models.ThirdParty.Translation.Key)}",
            $"{nameof(Models.ThirdParty.Translation.ValueLanguage)}",
            $"{nameof(Models.ThirdParty.Translation.Value)}",
        };

        [ActionName("ExportNoTranslations")]
        public Task<FileResult> ExportNoTranslationsAsync()
        {
            var fileName = $"{nameof(SnQMusicStore)}NoTranslations.csv";
            var fullItems = Translator.Instance.NoTranslations.Where(i => i.Key.Contains(".")).OrderBy(i => i.Key);
            var partItems = Translator.Instance.NoTranslations.Where(i => i.Key.Contains(".") == false).OrderBy(i => i.Key);
            var allItems = fullItems.Union(partItems);
            
            return Task.Factory.StartNew(() => ExportDefault(CsvHeader, allItems, fileName));
        }
        #endregion Export no translations
    }
}
//MdEnd

SnQMusicStore.AspMvc/Views/Shared/Composite.cshtml
@*@CodeCopy*@
@{
    @using CommonBase.Extensions
    @using SnQMusicStore.AspMvc.Models.Modules.View
    @using SnQMusicStore.AspMvc.Modules.Handler
    @using SnQMusicStore.AspMvc.Modules.Language
    @using SnQMusicStore.AspMvc.Modules.Session
    @using SnQMusicStore.AspMvc.Modules.View
    @model SnQMusicStore.AspMvc.Models.IdentityModel

    var viewBagInfo = new ViewBagWrapper(ViewBag);
    var sessionInfo = new SessionWrapper(Context.Session);

    viewBagInfo.Translate = Translator.TranslateIt;
    viewBagInfo.Controller = ViewContext.RouteData?.Values["controller"]?.ToString() ?? string.Empty;
    viewBagInfo.Action = ViewContext.RouteData?.Values["action"]?.ToString() ?? string.Empty;

    ViewData["Title"] = viewBagInfo.Title;
    <h1>@viewBagInfo.Title</h1>

    @if (string.IsNullOrEmpty(ErrorHandler.LastViewError) == false)
    {
        <div class="alert alert-danger" role="alert">
            @ErrorHandler.GetLastViewErrorAndClear()
        </div>
    }
    else
    {
        @if ((viewBagInfo.CommandMode & SnQMusicStore.AspMvc.Models.Modules.Common.CommandMode.Edit) > 0)
        {
            <p style="margin-top: 1em;">
                <a asp-action="Create" class="btn btn-outline-secondary">@viewBagInfo.TranslateFor("Create new...")</a>
            </p>
        }
        @if (Model.GetType().IsGenericTypeOf(typeof(CompositeModel<,,,,,>)))
        {
            var connectorProperty = Model.GetType().GetProperty("ConnectorModel");
            var connectorModel = connectorProperty?.GetValue(Model) as IdentityModel;
            var oneProperty = Model.GetType().GetProperty("OneModel");
            var oneModel = oneProperty?.GetValue(Model) as IdentityModel;
            var anotherProperty = Model.GetType().GetProperty("AnotherModel");
            var anotherModel = anotherProperty?.GetValue(Model)  as IdentityModel;

            if (connectorModel != null)
            {
                connectorModel.ViewBagInfo = viewBagInfo;
                @await Html.PartialAsync("_DisplayModel", connectorModel)
            }
            if (oneModel != null)
            {
                oneModel.ViewBagInfo = viewBagInfo;
                <h2>@viewBagInfo.TranslateFor("OneModel")</h2>
                @await Html.PartialAsync("_DisplayModel", oneModel)
            }
            if (anotherModel != null)
            {
                anotherModel.ViewBagInfo = viewBagInfo;
                <h2>@viewBagInfo.TranslateFor("AnotherModel")</h2>
                @await Html.PartialAsync("_DisplayModel", anotherModel)
            }
        }
        else if (Model.GetType().IsGenericTypeOf(typeof(CompositeModel<,,,,,>)))
        {
            var connectorProperty = Model.GetType().GetProperty("ConnectorModel");
            var connectorModel = connectorProperty?.GetValue(Model) as IdentityModel;
            var oneProperty = Model.GetType().GetProperty("OneModel");
            var oneModel = oneProperty?.GetValue(Model) as IdentityModel;
            var anotherProperty = Model.GetType().GetProperty("AnotherModel");
            var anotherModel = anotherProperty?.GetValue(Model) as IdentityModel;

            if (connectorModel != null)
            {
                viewBagInfo.ItemPrefix = "ConnectorModel";
                <h2>@viewBagInfo.TranslateFor("ConnectorModel")</h2>
                connectorModel.ViewBagInfo = viewBagInfo;
                @await Html.PartialAsync("_EditModel", connectorModel)
            }
            if (oneModel != null)
            {
                viewBagInfo.ItemPrefix = "OneModel";
                oneModel.ViewBagInfo = viewBagInfo;
                <h2>@viewBagInfo.TranslateFor("OneModel")</h2>
                @await Html.PartialAsync("_EditModel", oneModel)
            }
            if (anotherModel != null)
            {
                viewBagInfo.ItemPrefix = "AnotherModel";
                anotherModel.ViewBagInfo = viewBagInfo;
                <h2>@viewBagInfo.TranslateFor("AnotherModel")</h2>
                @await Html.PartialAsync("_EditModel", anotherModel)
            }
        }
    }
    <hr />
    @await Html.PartialAsync("_Back", new BackCmd() { BackText = viewBagInfo.TranslateFor("Back to List") })
}

SnQMusicStore.AspMvc/Views/Shared/DeleteDetail.cshtml
@*@CodeCopy*@
@{
    @using SnQMusicStore.AspMvc.Models.Modules.Common
    @using SnQMusicStore.AspMvc.Modules.Handler
    @using SnQMusicStore.AspMvc.Modules.Language
    @using SnQMusicStore.AspMvc.Modules.Session
    @using SnQMusicStore.AspMvc.Modules.View
    @using SnQMusicStore.AspMvc.Models.Modules.View
    @model SnQMusicStore.AspMvc.Models.MasterDetailModel

    var viewBagInfo = new ViewBagWrapper(ViewBag);
    var sessionInfo = new SessionWrapper(Context.Session);

    viewBagInfo.Translate = Translator.TranslateIt;
    viewBagInfo.Controller = ViewContext.RouteData?.Values["controller"]?.ToString() ?? string.Empty;
    viewBagInfo.Action = ViewContext.RouteData?.Values["action"]?.ToString() ?? string.Empty;

    if (Model.Master != null)
        Model.Master.ViewBagInfo = viewBagInfo;

    if (Model.Detail != null)
        Model.Detail.ViewBagInfo = viewBagInfo;

    viewBagInfo.HiddenNames.Add($"{Model?.Master?.GetType().Name}Id");
    viewBagInfo.IgnoreNames.Add($"{Model?.Master?.GetType().Name}Id");

    ViewData["Title"] = viewBagInfo.Title;
    <h2>@ViewData["Title"]</h2>
    <div class="d-flex bg-transparent">
        <div class="p-sm-2 mr-auto">
            <h4>@viewBagInfo.TranslateFor(viewBagInfo.Action)</h4>
        </div>
    </div>
    <hr />

    @await Html.PartialAsync("_DisplayModel", Model?.Master)
    <hr />

    viewBagInfo.ItemPrefix = nameof(Model.Detail);
    <form asp-action="@nameof(ActionMode.DeleteDetail)" method="post">

        @if (string.IsNullOrEmpty(ErrorHandler.LastViewError) == false)
        {
            <div class="alert alert-danger" role="alert">
                @ErrorHandler.GetLastViewErrorAndClear()
            </div>
        }
        else
        {

            <div class="alert alert-danger" role="alert">
                @viewBagInfo.TranslateFor("Should the entry be deleted?")
            </div>
        }

        @await Html.PartialAsync("_DisplayModel", Model?.Detail)
        <hr />
        @await Html.PartialAsync("_SubmitBack", new SubmitBackCmd() 
        {
            SubmitText = viewBagInfo.TranslateFor("Delete"), 
            SubmitCss = "btn btn-danger", 
            BackText = viewBagInfo.TranslateFor("Back to Details"), 
            BackAction = "Details",
            BackRouteValues = new { id = Model?.Master?.Id }
        })
    </form>
}

SnQMusicStore.AspMvc/Views/Shared/_CardBody.cshtml
@*@CodeCopy*@
@{
    @model SnQMusicStore.AspMvc.Models.IdentityModel

}

SnQMusicStore.AspMvc/Views/Shared/_DisplayGroup.cshtml
@*@CodeCopy*@
@{
    @using SnQMusicStore.AspMvc.Models.Modules.View
    @using SnQMusicStore.AspMvc.Modules.View
    @model DisplayViewModel

    if (Model != null)
    {
        var viewBagInfo = Model.ViewBagInfo ?? new ViewBagWrapper(ViewBag);
        var property = viewBagInfo.DisplayProperty;

        <dl class="row">
            <dt class="col-sm-2">
                @viewBagInfo.TranslateFor(Model.GetLabel(property))
            </dt>
            <dd class="col-sm-10">
                @await Html.PartialAsync("_DisplayControl", Model)
            </dd>
        </dl>
        viewBagInfo.Handled = true;
    }
}

SnQMusicStore.AspMvc/Views/Shared/_LoginMenu.cshtml
@*@CodeCopy*@
@*#if ACCOUNT_ON*@
@{
    @using Microsoft.AspNetCore.Mvc.Rendering
    @using SnQMusicStore.AspMvc.Modules.Session
    @using SnQMusicStore.AspMvc.Modules.Language

    var sessionInfo = new SessionWrapper(Context.Session);
    Func<string, string> translate = Translator.TranslateIt;
    Func<string, string> translateFor = pn => translate($"LoginMenu.{pn}");
    var mnoLogon = translateFor("Logon");
    var mnuLogout = translateFor("Logout");
    var mnuAccessAuth = translateFor("Access-Authorization");
    var mnuIdentityUser = translateFor("Identity-User");
    var mnuRoleMngr = translateFor("Role-Management");
    var mnuPwdChange = translateFor("Change password");
    var mnuPwdReset = translateFor("Reset password");
    var mnuReloadTranslations = translateFor("Reload translations");
    var mnuExportNoTranslations = translateFor("Export no translations");
    var mnuUser = string.Empty;

    if (sessionInfo.IsAuthenticated)
    {
        mnuUser = sessionInfo.LoginSession?.Name;
        if (sessionInfo.LoginSession != null && sessionInfo.LoginSession.IsRemoteAuth)
        {
            mnuUser = $"{mnuUser} [rm]";
        }
    }

    @if (sessionInfo.IsAuthenticated && sessionInfo.IsSessionAlive)
    {
        using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        {
            @Html.AntiForgeryToken()

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">@mnuUser</a>
                    <ul class="dropdown-menu">
                        @if (sessionInfo.HasRole("SysAdmin") == true)
                        {
                            <li class="dropdown-item">@Html.ActionLink(mnuAccessAuth, "Index", "AppAccesses", routeValues: null, htmlAttributes: null)</li>
                            <li class="dropdown-item">@Html.ActionLink(mnuIdentityUser, "Index", "IdentityUsers", routeValues: null, htmlAttributes: null)</li>
                            <li class="dropdown-item">@Html.ActionLink(mnuRoleMngr, "Index", "Roles", routeValues: null, htmlAttributes: null)</li>
                            <li class="dropdown-item">@Html.ActionLink(mnuPwdChange, "ChangePassword", "Account", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                            <li class="dropdown-item">@Html.ActionLink(mnuPwdReset, "ResetPassword", "Account", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                        }
                        else if (sessionInfo.HasRole("AppAdmin") == true)
                        {
                            <li class="dropdown-item">@Html.ActionLink(mnuAccessAuth, "Index", "AppAccesses", routeValues: null, htmlAttributes: null)</li>
                            <li class="dropdown-item">@Html.ActionLink(mnuIdentityUser, "Index", "IdentityUsers", routeValues: null, htmlAttributes: null)</li>
                            <li class="dropdown-item">@Html.ActionLink(mnuRoleMngr, "Index", "Roles", routeValues: null, htmlAttributes: null)</li>
                            <li class="dropdown-item">@Html.ActionLink(mnuPwdChange, "ChangePassword", "Account", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                            <li class="dropdown-item">@Html.ActionLink(mnuPwdReset, "ResetPassword", "Account", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                        }
                        else
                        {
                            <li class="dropdown-item">@Html.ActionLink(mnuPwdChange, "ChangePassword", "Account", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                        }
                        @if (Translator.Instance.HasLoaded)
                        {
                            <li class="dropdown-item">@Html.ActionLink(mnuReloadTranslations, "ReloadTranslations", "Translations", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                        }
                        <li class="dropdown-item">@Html.ActionLink(mnuExportNoTranslations, "ExportNoTranslations", "Translations", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                        <li class="dropdown-item"><a href="javascript:document.getElementById('logoutForm').submit()">@mnuLogout<i style="margin-left: 1em;" class="fas fa-sign-out-alt"></i></a></li>
                    </ul>
                </li>
            </ul>
        }
    }
    else
    {
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink(mnoLogon, "Logon", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
        </ul>
    }
}
@*#endif*@